{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "servicedesk-lite.namespace" . }}
  labels:
    {{- include "servicedesk-lite.labels" . | nindent 4 }}
{{- end }}
