apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: {{ include "servicedesk-lite.namespace" . }}
  labels:
    {{- include "servicedesk-lite.labels" . | nindent 4 }}
    app.kubernetes.io/component: notification-service
spec:
  ports:
    - name: metrics
      port: {{ .Values.service.notificationService.port }}
      targetPort: metrics
  selector:
    app.kubernetes.io/component: notification-service
    {{- include "servicedesk-lite.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: {{ include "servicedesk-lite.namespace" . }}
  labels:
    {{- include "servicedesk-lite.labels" . | nindent 4 }}
    app.kubernetes.io/component: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: notification-service
      {{- include "servicedesk-lite.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "servicedesk-lite.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: notification-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9091"
    spec:
      initContainers:
        - name: wait-postgres
          image: {{ .Values.postgres.image | quote }}
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "servicedesk-lite.fullname" . }}-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "servicedesk-lite.fullname" . }}-config
                  key: POSTGRES_USER
          command: ["sh", "-c"]
          args:
            - "until pg_isready -h postgres -U $POSTGRES_USER -d $POSTGRES_DB; do echo 'waiting for postgres...'; sleep 2; done"
        - name: wait-kafka
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args:
            - "until nc -z kafka 9092; do echo 'waiting for kafka...'; sleep 2; done"
      containers:
        - name: notification-service
          image: {{ printf "%s:%s" .Values.images.notificationService.repository .Values.images.notificationService.tag | quote }}
          imagePullPolicy: {{ .Values.images.notificationService.pullPolicy | quote }}
          ports:
            - name: metrics
              containerPort: 9091
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "servicedesk-lite.fullname" . }}-config
                  key: APP_ENV
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "servicedesk-lite.fullname" . }}-secret
                  key: DATABASE_URL
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "servicedesk-lite.fullname" . }}-config
                  key: KAFKA_BROKERS
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: {{ include "servicedesk-lite.fullname" . }}-config
                  key: KAFKA_TOPIC
            - name: KAFKA_GROUP_ID
              value: "notification-service"
            - name: KAFKA_START_OFFSET
              value: "first"
            - name: KAFKA_DLQ_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: {{ include "servicedesk-lite.fullname" . }}-config
                  key: KAFKA_DLQ_TOPIC
            - name: NOTIFY_MAX_ATTEMPTS
              value: "10"
            - name: NOTIFY_FORCE_FAIL
              value: "0"
            - name: NOTIFY_FORCE_FAIL_EVENT_TYPE
              value: ""
            - name: METRICS_ADDR
              value: ":9091"
          readinessProbe:
            httpGet:
              path: /readyz
              port: metrics
            initialDelaySeconds: 2
            periodSeconds: 3
            timeoutSeconds: 2
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          resources:
            {{- toYaml .Values.resources.notificationService | nindent 12 }}
