apiVersion: v1
kind: Secret
metadata:
  name: {{ include "servicedesk-lite.fullname" . }}-secret
  namespace: {{ include "servicedesk-lite.namespace" . }}
  labels:
    {{- include "servicedesk-lite.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  DATABASE_URL: {{ printf "postgres://%s:%s@postgres:5432/%s?sslmode=disable" .Values.postgres.user .Values.postgres.password .Values.postgres.database | quote }}
